apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: kafka-consumer
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker-hpa
    kustomize.toolkit.fluxcd.io/name: cluster-gitops
    kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
    app.kubernetes.io/component: run
    carto.run/workload-name: kafka-consumer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: kafka-consumer
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: worker-hpa
      carto.run/workload-name: kafka-consumer
      kustomize.toolkit.fluxcd.io/name: cluster-gitops
      kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
      tanzu.app.live.view: "true"
      tanzu.app.live.view.application.flavours: steeltoe
      tanzu.app.live.view.application.name: kafka-consumer
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/warroyo/steeltoe-kafka-consumer?sub_path=consumer
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: kafka-consumer
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: worker-hpa
        carto.run/workload-name: kafka-consumer
        kustomize.toolkit.fluxcd.io/name: cluster-gitops
        kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: kafka-consumer
    spec:
      containers:
      - image: 074754820263.dkr.ecr.us-west-2.amazonaws.com/tanzu-application-platform/kafka-consumer-dev@sha256:d1e14ba2701618fc17286f327059bda0d120d1cb29a975893267266facc05ca7
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-consumer-consumer-lag
  labels:
    app.kubernetes.io/part-of: kafka-consumer
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker-hpa
    kustomize.toolkit.fluxcd.io/name: cluster-gitops
    kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
    app.kubernetes.io/component: run
    carto.run/workload-name: kafka-consumer
spec:
  minReplicas: 1
  maxReplicas: 9
  metrics:
  - type: External
    external:
      metric:
        name: aws.kafka.sumoffsetlag
      target:
        averageValue: 30
        type: AverageValue
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer

